name: DevDungeon
version: 0.1
author: Devotedworker
main: com.devotedworker.plugin.DevDungeon
commands:
  generate:
    description: Generatesa a DungeonGenerationMap Generators map from the current DungeonAlgorithum
    usage: /DevotedDungeons:generate <Int|Width> <Int|Length> <Int|Height> <Bool|Build> <*Long|Seed>
depend: [WorldEdit]






















































